name = "wahoho-storefront"

workers_dev = true
main = "./dist/server/index.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2025-09-06"

[site]
  bucket = "./public"

[build]
  command = "npm run build"

[vars]
  SESSION_SECRET="foobar"
  PUBLIC_STOREFRONT_API_TOKEN="3b580e70970c4528da70c98e097c2fa0"
  PUBLIC_STOREFRONT_API_VERSION="2025-05"
  PUBLIC_STORE_DOMAIN="hydrogen-preview.myshopify.com"